### ISSUE TITLE
Deployment error on Windows 10

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/mean-booster#22]
```console
C:\Users\hf\Desktop\dev\mean-booster (master -> origin) (mean-booster@1.0.0)
λ npm run openshift

> mean-booster@1.0.0 openshift C:\Users\hf\Desktop\dev\mean-booster
> nodeshift --osc.strictSSL=false

2017-11-13T22:33:32.619Z INFO loading configuration
2017-11-13T22:33:32.650Z INFO using namespace myproject at https://192.168.99.100:8443
2017-11-13T22:33:32.665Z INFO creating archive of package.json, README.md, server.js, app
2017-11-13T22:33:32.749Z INFO creating build configuration mean-booster-s2i
2017-11-13T22:33:33.136Z INFO creating image stream mean-booster
2017-11-13T22:33:33.168Z INFO uploading binary archive C:\Users\hf\Desktop\dev\mean-booster/tmp/nodeshift/build/archive.tar
2017-11-13T22:35:55.808Z INFO binary upload complete
2017-11-13T22:35:55.816Z INFO waiting for build to finish
2017-11-13T22:35:55.882Z TRACE Receiving source from STDIN as archive ...
2017-11-13T22:35:55.883Z TRACE ---> Installing application source
2017-11-13T22:35:55.883Z TRACE cp: cannot stat '/tmp/src/./app/model': Permission denied
2017-11-13T22:35:55.884Z TRACE cp: cannot stat '/tmp/src/./app/resources': Permission denied
2017-11-13T22:35:55.885Z TRACE cp: cannot stat '/tmp/src/./app/controllers': Permission denied
2017-11-13T22:35:55.885Z TRACE cp: cannot stat '/tmp/src/./app/static': Permission denied
2017-11-13T22:35:55.886Z TRACE error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs:latest
2017-11-13T22:35:56.173Z ERROR build failed with message: Assemble script failed.
2017-11-13T22:35:56.176Z ERROR Error: Assemble script failed. Error: Assemble script failed.
    at module.exports (C:\Users\hf\Desktop\dev\mean-booster\node_modules\nodeshift\lib\binary-build.js:40:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mean-booster@1.0.0 openshift: `nodeshift --osc.strictSSL=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean-booster@1.0.0 openshift script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-13T22_35_56_221Z-debug.log

C:\Users\hf\Desktop\dev\mean-booster (master -> origin) (mean-booster@1.0.0)
```

Related to bucharest-gold/entente#179

**Comment by helio-frota** [comment]
The build phase works with `oc start-build mean-booster-s2i -n myproject`

![capture](https://user-images.githubusercontent.com/6443576/33571379-96244804-d90e-11e7-8298-dec9915de2e3.PNG)
![capture2](https://user-images.githubusercontent.com/6443576/33571380-9641c816-d90e-11e7-9dab-0a43764f81ce.PNG)
![capture3](https://user-images.githubusercontent.com/6443576/33571383-97687906-d90e-11e7-9c46-8c51a61e5f81.PNG)

**Comment by helio-frota** [comment]
After this: https://github.com/bucharest-gold/entente/issues/183#issue-282463975

I decided to try again , but I'm getting a different error message

using nodeshift: 0.9.0
![a](https://user-images.githubusercontent.com/6443576/34357831-2985e2e4-ea42-11e7-857a-dafa4e9384ff.PNG)



using nodeshift: 1.0.0
![b](https://user-images.githubusercontent.com/6443576/34357833-2ceab6ee-ea42-11e7-8226-3a2dbc589610.PNG)

**Comment by helio-frota** [comment]
is working overriding `.s2i/bin/assemble`

```sh
echo "---> ls /tmp/src/."
ls /tmp/src/.
echo "---> ls ./"
ls ./
echo "---> chmod 775 -R /tmp/src/."
chmod 775 -R /tmp/src/.
echo "---> chmod 775 -R ./"
chmod 775 -R ./
echo "---> Installing application source"
cp -Rf /tmp/src/. ./
...
```

After add this I was able to deploy using nodeshift:

![capture](https://user-images.githubusercontent.com/6443576/35020104-3b10a83c-fb22-11e7-8330-087b2081d2ae.PNG)

![capture2](https://user-images.githubusercontent.com/6443576/35020121-4ffee876-fb22-11e7-9aa5-2e7d21172a9f.PNG)

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/mean-booster/blob/master/.s2i/bin/assemble#L5-L6
